### ISSUE TITLE
Create support for Promises while waiting on Get/Post requests

### ISSUE THREAD

**Issue by aashnisshah** [cashapp/misk-web#509]

**Comment by adrw** [comment]
Desired functionality is a pattern of chaining requests in a specific order that are triggered as a side effect of a user interaction. 

Example
---

- User presses a `stop` button
- `/status/change/stop` POST request is sent
- `/status/refresh` GET request is sent
- Refreshed status data prompts relevant re-render of UI with newest status data

**Comment by adrw** [comment]
Create a simplePromise saga that takes a Promise and merges whatever it resolves to into the State

**Comment by adrw** [comment]
Support for `mergeSaga` merged in https://github.com/cashapp/misk-web/pull/641 that allows for asynchronous computation after a dispatched action.
