### ISSUE TITLE
Fix yargs deprecation warning

### ISSUE THREAD

**Issue by adrw** [cashapp/misk-web#520]
```
In future major releases of yargs, "parsed" will be a private field. Use the ret
urn value of ".parse()" or ".argv" instead
```

**Comment by codemile** [comment]
Are you importing yargs with TypeScript?

I found TypeScript was triggering this warning, because it would copy all of the module properties to a variable if you did this `import * as yargs from 'yargs';`.

There is no way to suppress the warning.

**Comment by codemile** [comment]
I was able to fix my issue by changing

```typescript
import * as yargs from 'yargs';
```

to this

```typescript
import yargs = require('yargs');
```
