### ISSUE TITLE
Update misk-web meta title descriptions to show service name in Browser tabs

### ISSUE THREAD

**Issue by aashnisshah** [cashapp/misk-web#548]
It would be great if we had the service name (or some other information) set as the Meta Title

<img width="237" alt="Screen Shot 2019-08-30 at 1 32 01 PM" src="https://user-images.githubusercontent.com/2501458/64040276-ae02e100-cb2a-11e9-823f-cbb1d925bbbd.png">

**Comment by adrw** [comment]
Merged with #590
